### ISSUE TITLE
As a mobility expert, I would like to see the new prototype of the mobility analytics online on https://analytics.opendatahub.testingmachine.eu/

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/mobility-analytics#33]
The user story relates to the integration of the PR https://github.com/noi-techpark/mobility-analytics/pull/32

**Comment by Piiit** [comment]
@rcavaliere This is OK, but please add it to the todo column, otherwise I do not understand priorities compared with other tasks... Thx

**Comment by Piiit** [comment]
@rcavaliere I published the PR, but authenticated retrieval of data does not work... need to investigate since `https://mobility.api.opendatahub.testingmachine.eu/tree/VMS/%2A/latest?limit=-1&distinct=true&where=sactive.eq.true: 0` with Authentication headers result in a 502 bad gateway

**Comment by Piiit** [comment]
@rcavaliere I found the issue, and solved it partially... but the analytics app downloads all data for each station (since VMS has huge metadata chunks, we run out of memory)... we need to investigate which fields are really required by each station type

**Comment by Piiit** [comment]
@rcavaliere You can test it now, but do not download VMS data for the moment

**Comment by rcavaliere** [comment]
@Piiit thanks! Is the issue related to the map or the chart part of the application? In case please contact Davide and Thomas for clarifications...

**Comment by Piiit** [comment]
@rcavaliere I improved the queries, which now download only obligatory data. The metadata field is not downloaded anymore, because in some cases it contain several MBytes of data. I suggest to make that a second call, after one clicks on "details" inside the sidepane, or an async call... The VMS download is now 250kb :-)

@noctho @davidebz FYI... I will open a new issue for that.

I think this issue can be closed and moved to done, since we are not ready for production due to other missing features
